pics/urls.py
from django.conf.urls import patterns, include, url

from .views import (
        ImageListView, ImageTableView, AlbumListView,
        YearCreateView, YearUpdateView,
        AlbumCreateView, AlbumUpdateView,
        ImageUploadView, ImageRepositionView,
        ImageSortView,
        )


urlpatterns = patterns('',
    url(r'^$', AlbumListView.as_view(), name='album_list'),
    url(r'^new/$', YearCreateView.as_view(), name='year_create'),
    url(r'^(?P<year>[\w_-]+)/edit/$', YearUpdateView.as_view(), name='year_update'),
    url(r'^(?P<year>[\w_-]+)/new/$', AlbumCreateView.as_view(), name='album_create'),
    url(r'^(?P<year>[\w_-]+)/(?P<album>[\w_-]+)/edit/$', AlbumUpdateView.as_view(), name='album_update'),
    url(r'^(?P<year>[\w_-]+)/(?P<album>[\w_-]+)/upload/$', ImageUploadView.as_view(), name='image_upload'),
    url(r'^(?P<year>[\w_-]+)/(?P<album>[\w_-]+)/$', ImageListView.as_view(), name='pics_album'),
    url(r'^(?P<year>[\w_-]+)/(?P<album>[\w_-]+)/table/$', ImageTableView.as_view(), name='image_table'),
    url(r'^(?P<year>[\w_-]+)/(?P<album>[\w_-]+)/reorder/$', ImageRepositionView.as_view(), name='image_reposition'),
    url(r'^(?P<year>[\w_-]+)/(?P<album>[\w_-]+)/sort/$', ImageSortView.as_view(), name='image_sort'),
)

picsdriver/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = (patterns('',
    # Examples:
    # url(r'^$', 'picsdriver.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('pics.urls')),
)
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

pics/models.py
import wand.image
from django.db import models
from django.core.urlresolvers import reverse
from django.core.files.storage import default_storage
from django.conf import settings
import re
import datetime
import tempfile

class Year(models.Model):
    number = models.CharField(max_length=40, unique=True)
    slug = models.CharField(max_length=40, unique=True)
    name = models.CharField(max_length=40)

    def __unicode__(self):
        return self.name

    def get_local_directory(self):
        return 'images/%s-%s' % (self.number, self.slug)

    class Meta:
        ordering = ('number',)

class Album(models.Model):
    year = models.ForeignKey(Year)
    number = models.CharField(max_length=40)
    slug = models.CharField(max_length=40)
    name = models.CharField(max_length=40)

    def get_absolute_url(self):
        return reverse('pics_album',
                kwargs={'year': self.year.slug,
                    'album': self.slug})

    def get_local_directory(self):
        return '%s/%s-%s' % (
                self.year.get_local_directory(),
                self.number,
                self.slug)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ('year', 'number',)
        unique_together = (('year', 'number'), ('year', 'slug'),)

def make_thumbnail(source_path, target_path):
    storage = default_storage
    with storage.open(source_path) as source_file, \
            wand.image.Image(file=source_file) as source_image, \
            source_image.clone() as target_image:
        width = settings.THUMBNAIL_WIDTH
        height = settings.THUMBNAIL_HEIGHT
        ratio = min(width / source_image.width, height / source_image.height)
        target_image.resize(
                width=int(ratio * source_image.width),
                height=int(ratio * source_image.height))
        with tempfile.TemporaryFile() as tmp_target:
            target_image.save(file=tmp_target)
            storage.save(target_path, tmp_target)


class Image(models.Model):
    album = models.ForeignKey(Album)
    position = models.IntegerField()
    filename = models.CharField(max_length=40)

    def get_local_path(self):
        return '%s/%s' % (self.album.get_local_directory(), self.filename)

    def get_local_thumbnail_path(self):
        return '%s/thumbs/%s' % (self.album.get_local_directory(), self.filename)

    def get_image_url(self):
        return default_storage.url(self.get_local_path())

    def get_thumbnail_url(self):
        return default_storage.url(self.get_local_thumbnail_path())

    def ensure_thumbnail(self):
        storage = default_storage
        source_path = self.get_local_path()
        target_path = self.get_local_thumbnail_path()
        try:
            source_time = storage.modified_time(source_path)
        except FileNotFoundError:
            return
        try:
            target_time = storage.modified_time(target_path)
            if target_time >= source_time:
                return
        except FileNotFoundError:
            pass
        make_thumbnail(source_path, target_path)

    @property
    def exif_datetime(self):
        try:
            with default_storage.open(self.get_local_path()) as f:
                with wand.image.Image(file=f) as img:
                    timestring = img.metadata['exif:DateTimeOriginal']
                    o = re.match(r'(....):(..):(..) (..):(..):(..)', timestring)
                    if not o:
                        return None
                    else:
                        return datetime.datetime(*[int(o.group(1+i))
                            for i in range(6)])
        except FileNotFoundError:
            return None

    @property
    def mtime(self):
        try:
            return default_storage.modified_time(self.get_local_path())
        except FileNotFoundError:
            return None

    class Meta:
        ordering = ('position',)
        unique_together = (('album', 'filename'),)

pics/views.py
from django.views.generic import ListView, UpdateView, CreateView, FormView, View
from .models import Year, Album, Image
from django.core.urlresolvers import reverse
from django import forms
from django.core.files.storage import default_storage
from django.shortcuts import get_object_or_404
import os
from django.db import transaction
import json
from django.http import HttpResponse, HttpResponseRedirect

class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        exclude = ('year',)

class AlbumListView(ListView):
    model = Year

class ImageListView(ListView):
    model = Image

    def get_context_data(self, **kwargs):
        context_data = super(ImageListView, self).get_context_data(**kwargs)
        context_data['year'] = Year.objects.get(slug=self.kwargs['year'])
        context_data['album'] = Album.objects.get(
                year__slug=self.kwargs['year'],
                slug=self.kwargs['album'])
        return context_data

    def get_queryset(self):
        return Image.objects.filter(
                album__slug=self.kwargs['album'],
                album__year__slug=self.kwargs['year'])

class ImageTableView(ImageListView):
    template_name = 'pics/image_table.html'

class SingleAlbumMixin(object):
    def get_year(self):
        return Year.objects.get(slug=self.kwargs['year'])

class YearUpdateView(UpdateView):
    model = Year

    def get_object(self):
        return Year.objects.get(slug=self.kwargs['year'])

    def get_success_url(self):
        return reverse('album_list')

class AlbumUpdateView(UpdateView, SingleAlbumMixin):
    model = Album
    form_class = AlbumForm

    def get_context_data(self, **kwargs):
        context_data = super(AlbumUpdateView, self).get_context_data(**kwargs)
        context_data['year'] = self.get_year()
        return context_data

    def get_object(self):
        return Album.objects.get(
                year__slug=self.kwargs['year'],
                slug=self.kwargs['album'])

    def form_valid(self, form):
        album = form.save()
        for image in album.image_set.all():
            image.ensure_thumbnail()
        return super(AlbumUpdateView, self).form_valid(form)

class YearCreateView(CreateView):
    model = Year

    def form_valid(self, form):
        form.save()
        return super(YearCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('album_list')

class AlbumCreateView(CreateView, SingleAlbumMixin):
    model = Album
    form_class = AlbumForm

    def get_context_data(self, **kwargs):
        context_data = super(AlbumCreateView, self).get_context_data(**kwargs)
        context_data['year'] = self.get_year()
        return context_data

    def form_valid(self, form):
        album = form.save(commit=False)
        album.year = self.get_year()
        album.save()
        return super(AlbumCreateView, self).form_valid(form)

def AjaxResponse(payload, **kwargs):
    return HttpResponse(json.dumps(payload), **kwargs)

def AjaxBadRequest(error_message):
    return AjaxResponse({'error': error_message}, content_type='application/json', status=400)

def AjaxResponseOK():
    # 204 No Content
    return HttpResponse(status=204)

class ImageUploadView(View):
    def get_album(self):
        return Album.objects.get(
                year__slug=self.kwargs['year'],
                slug=self.kwargs['album'])

    def get_success_url(self):
        album = self.get_album()
        return reverse('album_update', kwargs={
            'year': album.year.slug,
            'album': album.slug})

    def post(self, request, **kwargs):
        self.request = request
        self.kwargs = kwargs

        ajax = bool(request.GET['ajax']) if 'ajax' in request.GET else False

        album = self.get_album()
        directory = album.get_local_directory()

        files = request.FILES.getlist('image')
        position = 0
        for image in album.image_set.all():
            position = max(position, image.position)
        position += 1
        result = []

        for f in files:
            filename = default_storage.get_valid_name(f.name)
            path = '%s/%s' % (directory, filename)
            path = default_storage.save(path, f)
            dir_name, file_name = os.path.split(path)
            assert dir_name == directory
            i = Image(album=album, position=position, filename=file_name)
            position += 1
            i.save()
            i.ensure_thumbnail()
            result.append({'pk': i.pk, 'filename': i.filename, 'original_filename': f.name, 'thumbnail': i.get_thumbnail_url()})

        if ajax:
            return AjaxResponse(result)
        else:
            return HttpResponseRedirect(self.get_success_url())

class ImageRepositionView(View):
    def post(self, request, **kwargs):
        self.kwargs = kwargs

        album = get_object_or_404(Album, 
                year__slug=self.kwargs['year'],
                slug=self.kwargs['album'])

        try:
            image_pks = list(int(x) for x in request.POST['images'].split(','))
        except (KeyError, ValueError):
            return AjaxBadRequest('Incorrect or missing "images"')

        prev = None
        for pk in sorted(image_pks):
            if pk == prev:
                return AjaxBadRequest('Duplicate pk %s' % pk)
            prev = pk

        images = album.image_set.all().in_bulk(image_pks)
        if frozenset(image_pks) != frozenset(images.keys()):
            return AjaxBadRequest('Some images not found')

        min_position = min(image.position for image in images.values())
        max_position = max(image.position for image in images.values())

        if max_position - min_position + 1 >= len(image_pks):
            positions = tuple(sorted(image.position for image in images.values()))
        else:
            positions = tuple(range(min_position, min_position + len(image_pks)))

        assert len(positions) == len(image_pks)

        with transaction.commit_on_success():
            for pk, position in zip(image_pks, positions):
                Image.objects.filter(pk=pk).update(position=position)

        return AjaxResponseOK()

class ImageSortView(View):
    def post(self, request, **kwargs):
        self.request = request
        self.kwargs = kwargs

        album = get_object_or_404(Album, 
                year__slug=self.kwargs['year'],
                slug=self.kwargs['album'])

        if 'by_name' in request.POST:
            key = lambda image: image.filename
        elif 'by_time' in request.POST:
            def force_naive(dt):
                return dt.replace(tzinfo=None)
            key = lambda image: force_naive(image.exif_datetime or image.mtime)
        else:
            return AjaxBadRequest('You must specify by_name or by_time')

        images = list(album.image_set.all())
        images.sort(key=key)
        pos = 1
        with transaction.commit_on_success():
            for image in images:
                image.position = pos
                image.save()
                pos += 1

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('pics_album', kwargs=self.kwargs)

pics/templates/pics/album_form.html
{% extends "pics/base.html" %}
{% block content %}
<form method="post">{% csrf_token %}
<p>Year: {{ year }}</p>
{{ form.as_p }}
<input type="submit" value="Create/update" />
</form>
{% if album %}
<form method="post" action="{% url 'image_sort' year=year.slug album=album.slug %}">{% csrf_token %}
    <input type="submit" name="by_name" value="Sort by filename" />
    <input type="submit" name="by_time" value="Sort by time" />
</form>
<form method="post" enctype="multipart/form-data" action="{% url 'image_upload' year=year.slug album=album.slug %}">{% csrf_token %}
Select images to upload:
<input multiple="multiple" type="file" name="image" />
<input type="submit" value="Upload" />
</form>
{% endif %}

{% endblock %}

pics/templates/pics/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<link rel="stylesheet" type="text/css" href="{% static 'pics/css/style.css' %}" />
{% block head %}{% endblock %}
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

pics/templates/pics/image_list.html
{% extends "pics/base.html" %}
{% load static %}
{% block head %}
<script type="text/javascript" src="http://code.jquery.com/jquery-2.0.3.min.js"></script>
<script type="text/javascript" src="http://code.jquery.com/ui/1.10.3/jquery-ui.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'pics/css/image_list.css' %}" />
<script type="text/javascript" src="{% static 'pics/js/image_list.js' %}"></script>
{% endblock %}
{% block content %}
<h1>{{ year }}</h1>
<h2>{{ album }}</h2>
<p><a href="{% url 'album_update' year=year.slug album=album.slug %}">Edit...</a></p>
<form action="upload/" method="post" enctype="multipart/form-data" onsubmit="handle_files(this.filesField)">
{% csrf_token %}
<p>Upload more images: <input type="file" name="filesField" multiple="multiple" onchange="handle_files(this)" /></p>
<p id="upload_progress"></p>
</form>
<ul class="imagegrid">
{% for image in image_list %}
<li data-pk="{{ image.pk }}">
<img src="{{ image.get_thumbnail_url }}" />
</li>
{% endfor %}
</ul>
{% endblock %}

pics/templates/pics/image_table.html
{% extends "pics/base.html" %}
{% block content %}
<h1>{{ year }}</h1>
<h2>{{ album }}</h2>
<p><a href="{% url 'album_update' year=year.slug album=album.slug %}">Edit...</a></p>
<table class="images">
<thead>
<tr>
<th>Name</th>
<th>EXIF date</th>
<th>Last modified</th>
</tr>
</thead>
<tbody>
{% for image in image_list %}
<tr>
<td><a href="{{ image.get_image_url }}" target="_blank">
        {{ image.filename }}</a></td>
<td>{{ image.exif_datetime }}</td>
<td>{{ image.mtime }}</td>
</tr>
{% endfor %}
</tbody>
</table>
{% endblock %}

pics/templates/pics/year_form.html
{% extends "pics/base.html" %}
{% block content %}
<form method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Create/update" />
</form>
{% endblock %}

pics/templates/pics/year_list.html
{% extends "pics/base.html" %}
{% block content %}
{% for year in year_list %}
<h2>[{{ year.name }}]</h2>
<ul class="albums">
{% for album in year.album_set.all %}
<li>[<a href="{{ album.get_absolute_url }}">{{ album.name }}</a>]</li>
{% endfor %}
<li>[<a href="{% url 'album_create' year=year.slug %}">New</a>]</li>
</ul>
{% endfor %}
<h2>[<a href="{% url 'year_create' %}">New</a>]</h2>
{% endblock %}